//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_NoteConverter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_calendar
    {
        public int id { get; set; }
        public string users_name { get; set; }
        public string realname { get; set; }
        public System.DateTime date { get; set; }
        public string from_time { get; set; }
        public string to_time { get; set; }
        public string event_type { get; set; }
        public string event_code { get; set; }
        public string customer { get; set; }
        public int status { get; set; }
        public string med_cert { get; set; }
        public int fine { get; set; }
        public string rec_by { get; set; }
    }
}
