//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_NoteConverter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_calendar2
    {
        public int id { get; set; }
        public string users_name { get; set; }
        public string realname { get; set; }
        public System.DateTime date { get; set; }
        public string from_time { get; set; }
        public string to_time { get; set; }
        public string event_type { get; set; }
        public Nullable<int> event_code_id { get; set; }
        public string event_code { get; set; }
        public string customer { get; set; }
        public Nullable<int> status { get; set; }
        public string med_cert { get; set; }
        public Nullable<int> fine { get; set; }
        public string series { get; set; }
        public string rec_by { get; set; }
    
        public virtual note_istab2 note_istab2 { get; set; }
    }
}
