//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_NoteConverter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class serial
    {
        public int id { get; set; }
        public string sernum { get; set; }
        public string oldnum { get; set; }
        public string version { get; set; }
        public string contact { get; set; }
        public string position { get; set; }
        public string prenam { get; set; }
        public string compnam { get; set; }
        public string addr01 { get; set; }
        public string addr02 { get; set; }
        public string addr03 { get; set; }
        public string zipcod { get; set; }
        public string telnum { get; set; }
        public string faxnum { get; set; }
        public string busityp { get; set; }
        public string busides { get; set; }
        public Nullable<System.DateTime> purdat { get; set; }
        public Nullable<System.DateTime> expdat { get; set; }
        public string howknown { get; set; }
        public string area { get; set; }
        public string branch { get; set; }
        public Nullable<System.DateTime> manual { get; set; }
        public string upfree { get; set; }
        public string refnum { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> chgdat { get; set; }
        public string verext { get; set; }
        public Nullable<System.DateTime> verextdat { get; set; }
        public Nullable<int> users_id { get; set; }
        public string users_name { get; set; }
        public Nullable<int> dealer_id { get; set; }
        public string dealer_dealer { get; set; }
    }
}
