//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_NoteConverter.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sn_netEntities : DbContext
    {
        public sn_netEntities()
            : base("name=sn_netEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Model.cloud_srv> cloud_srv { get; set; }
        public DbSet<Model.d_msg> d_msg { get; set; }
        public DbSet<Model.dealer> dealer { get; set; }
        public DbSet<Model.event_calendar> event_calendar { get; set; }
        public DbSet<Model.istab> istab { get; set; }
        public DbSet<Model.ma> ma { get; set; }
        public DbSet<Model.mac_allowed> mac_allowed { get; set; }
        public DbSet<Model.note_calendar> note_calendar { get; set; }
        public DbSet<Model.problem> problem { get; set; }
        public DbSet<Model.serial> serial { get; set; }
        public DbSet<Model.serial_password> serial_password { get; set; }
        public DbSet<Model.spy_log> spy_log { get; set; }
        public DbSet<Model.support_note> support_note { get; set; }
        public DbSet<Model.support_note_comment> support_note_comment { get; set; }
        public DbSet<Model.training_calendar> training_calendar { get; set; }
        public DbSet<Model.users> users { get; set; }
        public DbSet<Model.websession> websession { get; set; }
    }
}
