//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_NoteConverter.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sn_notesEntities : DbContext
    {
        public sn_notesEntities()
            : base("name=sn_notesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<event_calendar2> event_calendar2 { get; set; }
        public DbSet<note_calendar2> note_calendar2 { get; set; }
        public DbSet<note_comment2> note_comment2 { get; set; }
        public DbSet<note_istab2> note_istab2 { get; set; }
        public DbSet<note2> note2 { get; set; }
        public DbSet<training_calendar2> training_calendar2 { get; set; }
    }
}
