//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_NoteConverter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class spy_log
    {
        public int id { get; set; }
        public string users_name { get; set; }
        public string serial_sernum { get; set; }
        public string compnam { get; set; }
        public System.DateTime date { get; set; }
        public string time { get; set; }
    }
}
