//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_NoteConverter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.dealer = new HashSet<dealer>();
            this.problem = new HashSet<problem>();
            this.websession = new HashSet<websession>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string userpassword { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public int level { get; set; }
        public string usergroup { get; set; }
        public string status { get; set; }
        public string allowed_web_login { get; set; }
        public string training_expert { get; set; }
        public int max_absent { get; set; }
        public System.DateTime create_at { get; set; }
        public System.DateTime last_use { get; set; }
        public string rec_by { get; set; }
    
        public virtual ICollection<dealer> dealer { get; set; }
        public virtual ICollection<problem> problem { get; set; }
        public virtual ICollection<websession> websession { get; set; }
    }
}
